language: python

sudo: false

cache:
  directories:
    - "~/.platformio"
    - $HOME/.cache/pip

env:
- PLATFORMIO_CI_SRC=examples/CommandSniffer
- PLATFORMIO_CI_SRC=examples/DataLogger
- PLATFORMIO_CI_SRC=examples/StartLight

install:
- pip install -U platformio
- pio update

script:
- pio ci -v -l src -O framework=arduino -b uno -b pico -b nodemcuv2
- pio ci -v -l src -O framework=mbed -b nucleo_f446re -b bbcmicrobit
