name: Test Build

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        src: [examples/CommandSniffer, examples/DataLogger, examples/StartLight]
        framework: [mbed, arduino]
        include:
          - framework: mbed
            boards: -b nucleo_f446re
          - framework: arduino
            boards: -b uno -b pico -b nodemcuv2
    steps:
      - uses: actions/checkout@v2
      - name: Install platformio and its dependencies
        run: |
          python -m pip install --upgrade pip
          pip install platformio
          pio update
      - name: Compile ${{ matrix.framework }}
        run: |
          pio ci -v -l src -O framework=${{ matrix.framework }} ${{ matrix.boards }}
        env:
          PLATFORMIO_CI_SRC: ${{ matrix.src }}
